name: Checks
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: app/pnpm-lock.yaml
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
